name: CI - HealthTrack

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilar proyecto
        run: mvn clean install -DskipTests

      - name: Ejecutar pruebas unitarias
        run: mvn test

      - name: Generar reporte de cobertura JaCoCo
        run: mvn jacoco:report

      - name: Subir reporte JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: cobertura
          path: target/site/jacoco/index.html

      - name: Análisis con SonarCloud
        run: mvn sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
